Build built-in Xcode project

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -14,8 +14,10 @@ trigger_map:
 
 app:
   envs:
-    - BITRISE_PROJECT_PATH: ldc-build-runtime.tmp/TestRunner/TestRunner.xcodeproj
-    - BITRISE_SCHEME: TestRunner
+    # - BITRISE_PROJECT_PATH: ldc-build-runtime.tmp/TestRunner/TestRunner.xcodeproj
+    # - BITRISE_SCHEME: TestRunner
+    - BITRISE_PROJECT_PATH: bitrise-test.xcodeproj
+    - BITRISE_SCHEME: bitrise-test
     - BITRISE_EXPORT_METHOD: development
     - LLVM_VERSION: 14.0.3
     - HOST_LDC_VERSION: 1.24.0
@@ -30,98 +32,98 @@ workflows:
       - certificate-and-profile-installer@1.10.3:
           title: Install profile and certificate
 
-      - git-clone@6:
-          title: Clone LDC
-          inputs:
-            - repository_url: https://github.com/ldc-developers/ldc
-
-      - script@1.1.6:
-          title: Download LLVM
-          inputs:
-            - content: |-
-                #!/bin/bash
-                set -ex
-                curl -fL --retry 3 --max-time 300 "https://github.com/ldc-developers/llvm-project/releases/download/ldc-v${LLVM_VERSION}/llvm-${LLVM_VERSION}-osx-x86_64.tar.xz" -o llvm.tar.xz
-                tar xf llvm.tar.xz
-                envman add --key LLVM_ROOT_DIR --value "$(pwd)/llvm-${LLVM_VERSION}-osx-x86_64"
-
-      - script@1.1.6:
-          title: Download LDC
-          inputs:
-            - content: |-
-                #!/bin/bash
-                set -ex
-                curl -fL --retry 3 --max-time 300 "https://github.com/ldc-developers/ldc/releases/download/v${HOST_LDC_VERSION}/ldc2-${HOST_LDC_VERSION}-osx-x86_64.tar.xz" -o ldc.tar.xz
-                tar xf ldc.tar.xz
-                envman add --key PATH --value "$(pwd)/ldc2-${HOST_LDC_VERSION}-osx-x86_64/bin:$PATH"
-
-      - script@1.1.6:
-          title: Build LDC
-          deps:
-            brew:
-              - name: cmake
-              - name: ninja
-          inputs:
-            - content: |-
-                #!/bin/bash
-                set -ex
-                mkdir build
-                cd build
-                cmake -G Ninja .. \
-                  -DD_COMPILER=ldmd2 \
-                  -DBUILD_SHARED_LIBS=OFF \
-                  -DCMAKE_BUILD_TYPE=Release \
-                  -DLLVM_ROOT_DIR="$LLVM_ROOT_DIR" \
-                  -DLDC_LINK_MANUALLY=OFF
-                ninja -j2
-                envman add --key LDC_BINARY --value "$(pwd)/bin/ldc2"
-
-      - script@1.1.6:
-          title: Cross-compile (iOS/x86_64) druntime & Phobos
-          deps:
-            brew:
-              - name: cmake
-              - name: ninja
-          inputs:
-            - content: |-
-                #!/bin/bash
-                set -ex
-                build/bin/ldc-build-runtime \
-                  --buildDir="ldc-build-runtime.x86_64" \
-                  --cFlags="-target;x86_64-apple-ios${IOS_VERSION}" \
-                  --dFlags="-mtriple=x86_64-apple-ios${IOS_VERSION};-fvisibility=hidden" \
-                  --ldcSrcDir=. \
-                  --ninja \
-                  -j 2 \
-                  CMAKE_SYSTEM_NAME=iOS \
-                  CMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk \
-                  CMAKE_OSX_ARCHITECTURES=x86_64 \
-                  CMAKE_OSX_DEPLOYMENT_TARGET="${IOS_VERSION}" \
-                  BUILD_SHARED_LIBS=OFF
-
-      - script@1.1.6:
-          title: Cross-compile (iOS/arm64) druntime & Phobos, incl. debug unittest runners
-          deps:
-            brew:
-              - name: cmake
-              - name: ninja
-          inputs:
-            - content: |-
-                #!/bin/bash
-                set -ex
-                build/bin/ldc-build-runtime \
-                  --cFlags="-target;arm64-apple-ios${IOS_VERSION}" \
-                  --dFlags="-mtriple=arm64-apple-ios${IOS_VERSION};-fvisibility=hidden" \
-                  --ldcSrcDir=. \
-                  --ninja \
-                  -j 2 \
-                  CMAKE_SYSTEM_NAME=iOS \
-                  CMAKE_OSX_ARCHITECTURES=arm64 \
-                  CMAKE_OSX_DEPLOYMENT_TARGET="${IOS_VERSION}" \
-                  BUILD_SHARED_LIBS=OFF
-
-                cd ldc-build-runtime.tmp
-                ninja -j2 druntime-test-runner-debug phobos2-test-runner-debug
+      # - git-clone@6:
+      #     title: Clone LDC
+      #     inputs:
+      #       - repository_url: https://github.com/ldc-developers/ldc
+      #
+      # - script@1.1.6:
+      #     title: Download LLVM
+      #     inputs:
+      #       - content: |-
+      #           #!/bin/bash
+      #           set -ex
+      #           curl -fL --retry 3 --max-time 300 "https://github.com/ldc-developers/llvm-project/releases/download/ldc-v${LLVM_VERSION}/llvm-${LLVM_VERSION}-osx-x86_64.tar.xz" -o llvm.tar.xz
+      #           tar xf llvm.tar.xz
+      #           envman add --key LLVM_ROOT_DIR --value "$(pwd)/llvm-${LLVM_VERSION}-osx-x86_64"
+      #
+      # - script@1.1.6:
+      #     title: Download LDC
+      #     inputs:
+      #       - content: |-
+      #           #!/bin/bash
+      #           set -ex
+      #           curl -fL --retry 3 --max-time 300 "https://github.com/ldc-developers/ldc/releases/download/v${HOST_LDC_VERSION}/ldc2-${HOST_LDC_VERSION}-osx-x86_64.tar.xz" -o ldc.tar.xz
+      #           tar xf ldc.tar.xz
+      #           envman add --key PATH --value "$(pwd)/ldc2-${HOST_LDC_VERSION}-osx-x86_64/bin:$PATH"
+      #
+      # - script@1.1.6:
+      #     title: Build LDC
+      #     deps:
+      #       brew:
+      #         - name: cmake
+      #         - name: ninja
+      #     inputs:
+      #       - content: |-
+      #           #!/bin/bash
+      #           set -ex
+      #           mkdir build
+      #           cd build
+      #           cmake -G Ninja .. \
+      #             -DD_COMPILER=ldmd2 \
+      #             -DBUILD_SHARED_LIBS=OFF \
+      #             -DCMAKE_BUILD_TYPE=Release \
+      #             -DLLVM_ROOT_DIR="$LLVM_ROOT_DIR" \
+      #             -DLDC_LINK_MANUALLY=OFF
+      #           ninja -j2
+      #           envman add --key LDC_BINARY --value "$(pwd)/bin/ldc2"
+      #
+      # - script@1.1.6:
+      #     title: Cross-compile (iOS/x86_64) druntime & Phobos
+      #     deps:
+      #       brew:
+      #         - name: cmake
+      #         - name: ninja
+      #     inputs:
+      #       - content: |-
+      #           #!/bin/bash
+      #           set -ex
+      #           build/bin/ldc-build-runtime \
+      #             --buildDir="ldc-build-runtime.x86_64" \
+      #             --cFlags="-target;x86_64-apple-ios${IOS_VERSION}" \
+      #             --dFlags="-mtriple=x86_64-apple-ios${IOS_VERSION};-fvisibility=hidden" \
+      #             --ldcSrcDir=. \
+      #             --ninja \
+      #             -j 2 \
+      #             CMAKE_SYSTEM_NAME=iOS \
+      #             CMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk \
+      #             CMAKE_OSX_ARCHITECTURES=x86_64 \
+      #             CMAKE_OSX_DEPLOYMENT_TARGET="${IOS_VERSION}" \
+      #             BUILD_SHARED_LIBS=OFF
+      #
+      # - script@1.1.6:
+      #     title: Cross-compile (iOS/arm64) druntime & Phobos, incl. debug unittest runners
+      #     deps:
+      #       brew:
+      #         - name: cmake
+      #         - name: ninja
+      #     inputs:
+      #       - content: |-
+      #           #!/bin/bash
+      #           set -ex
+      #           build/bin/ldc-build-runtime \
+      #             --cFlags="-target;arm64-apple-ios${IOS_VERSION}" \
+      #             --dFlags="-mtriple=arm64-apple-ios${IOS_VERSION};-fvisibility=hidden" \
+      #             --ldcSrcDir=. \
+      #             --ninja \
+      #             -j 2 \
+      #             CMAKE_SYSTEM_NAME=iOS \
+      #             CMAKE_OSX_ARCHITECTURES=arm64 \
+      #             CMAKE_OSX_DEPLOYMENT_TARGET="${IOS_VERSION}" \
+      #             BUILD_SHARED_LIBS=OFF
+      #
+      #           cd ldc-build-runtime.tmp
+      #           ninja -j2 druntime-test-runner-debug phobos2-test-runner-debug
 
       - xcode-build-for-test@0.4.0:
           title: Build Xcode Project
